language: node_js

node_js:
- '6'

script: npm run build

before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36

deploy:
  provider: s3
  access_key_id: AKIAIRYPQIE3DGQE36TA
  secret_access_key:
    secure: aFLH7ZKbFxSDeXvewW3blD46bHwAepnvNLO/D4sIkagnv72VbW7DFGyy1548+6x5KgF2AkT0dkkvyygxK0JhotlRPbSQKKivZjTBB6FtKnW4HQA2qOLo8AlY0b1Z6jqKKES9Uc1V1ScSADZb49IFTT1/VqQA0wAc4b7Ir2shF2GZrtXtq05ggKZj28uvu4rrUJIRCMuyfgOU+rm7bwWnSL5RC2CdEaeD9kV0UCbX4gdEU4g+pWZsug4SpoKClZBGFvhOqM/xDdTD1cFpHHwoS31Z5We4dTdbxpsZGKdUkesLrk42YMc9ILLrNJEeceAxNgmuWk0qYeF72YBbFzYd0fe+SsDaF4Vv3dX8U4GU8D2j2ywkiiSIyuv8mJ405l6N9NX8XUJaMZaGNvTfk4y3UrLOkjFWTNGMyE2xKkuzkbFbhJn6CWWWtkXxomk2WeyAKo3NIfUqD9dtww5FmEdFUB2CCoicp+Rz9azA3+TXi/4m+Aar7GwEeuR8CQ9adwMUJYdi7ZIInVLBENqOhWKvhhrHi/uvtY3f7vYsUWOPMNy/THUzI5uGJvMsnl9W5BncseLfpjWhH8zJErWbC0Fj8c4GwOacD0WzwfYyzK1deIdklK9xTo8tfneGxX62NjvbcZsBA3gS06VZyrWP+vSmeG4cKgJNKVBNl714MHPNOes=
  bucket: dev.1989generationinitiative.org
  skip_cleanup: true
  region: eu-central-1
  local_dir: dist
  cache_control: max-age=604800

cache:
  yarn: true
  directories:
  - node_modules
