language: node_js

node_js:
- '6'

script: npm run build
after_success: npm run deploy
after_script:
  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then npm run promoteToLive; fi'

cache:
  yarn: true
  directories:
  - node_modules
