version: '2'
services:

  server:
    image: library/nginx:1.11.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/etc/nginx/html:ro
      - ./infrastructure/nginx/thecodestein.com.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  server-arm:
    image: ricard0javier/nginx-arm
    ports:
      - "80:80"
    volumes:
      - ./dist:/etc/nginx/html:ro
      - ./infrastructure/nginx/thecodestein.com.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  api:
    image: ricard0javier/the-codestein-backend
    volumes:
      - ./infrastructure/README.md:/usr/share/www/static/articles/README.md:ro

  api-only:
    image: ricard0javier/the-codestein-backend
    volumes:
      - ./infrastructure/README.md:/usr/share/www/static/articles/README1.md:ro
      - ./infrastructure/README.md:/usr/share/www/static/articles/README2.md:ro
      - ./infrastructure/README.md:/usr/share/www/static/articles/README3.md:ro
    ports:
      - 80:8080

  deepstream:
    image: deepstreamio/deepstream.io
    ports:
      - "6020:6020"
      - "6021:6021"
    volumes:
      - ./deepstream/conf:/usr/local/deepstream/conf
      - ./deepstream/var:/usr/local/deepstream/var
    depends_on:
      - redis
      - rethinkdb


  deepstream-search-provider:
    image: deepstreamio/deepstream.io-provider-search-rethinkdb
    environment:
      - DEEPSTREAM_HOST=deepstream
      - DEEPSTREAM_PORT=6021
      - RETHINKDB_HOST=rethinkdb
    depends_on:
      - deepstream


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


  rethinkdb:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "7080:8080"
    volumes:
      - ./deepstream/rethinkdb_data:/data/rethinkdb_data
